### ISSUE TITLE
Text color for notifications

### ISSUE THREAD

**Issue by Technetium1** [IulianOctavianPreda/ChromeThemes#1]
Where it says `tech` is nearly unreadable.
![image](https://user-images.githubusercontent.com/9877150/90195543-b2ee8e00-dd97-11ea-858a-1ee16c33f182.png)

**Comment by IulianOctavianPreda** [comment]
Hello,

Thank you for your feedback.
From my understanding, you cannot change the text colors of push notifications using a custom theme.

More so, in the past, as a developer, you could send custom push notifications that could include HTML and styling, but currently, even that is impossible. Chrome and other web browsers have full control over how the title, subtitle, and the text appears, except for icons, mostly, you can change its colour.
The one thing that can still send rich-text notifications is a chrome extension since it is verified before being published.
If this is the case, please try contacting jumpin chat.

Best regards,
Iulian

References:
https://stackoverflow.com/questions/19833814/styling-html5-desktop-notifications
https://developer.chrome.com/extensions/notifications
https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification
https://developers.google.com/web/ilt/pwa/introduction-to-push-notifications
https://developers.google.com/web/fundamentals/push-notifications/display-a-notification
https://docs.pushtechnology.com/cloud/latest/manual/html/administratorguide/pushnotifications/pnb_json_notification.html
https://documentation.onesignal.com/docs/push-notification-guide

**Comment by Technetium1** [comment]
Thank you for your help!

**Comment by IulianOctavianPreda** [comment]
No problem,
Also if you activate dark mode in Windows(I suppose you have Windows from your screenshot) the notifications should have inverted colors too.

[Windows dark theme](https://www.pcmag.com/how-to/how-to-enable-dark-mode-in-windows-10#:~:text=To%20enable%20dark%20mode%20in%20the%20Windows%2010%20May%202019,and%20the%20built-in%20apps)

**Comment by Technetium1** [comment]
I do in fact, that makes me wonder...
